apiVersion: apps/v1  # Kubernetes API version 
kind: Deployment     # Resource type is deployment
metadata:            # Metadata aboutmthe Deployment
  name: frontend
  labels:
    app: my-nginx
    tier: frontend
spec:
  selector:  # The selector is used to "select" the template to use(based on labels).
    matchLabels:
      tier: frontend
  template:  # Template to use to create the Pod/Containers (note that the selector matches the label)
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: my-nginx
        image: nginx:alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /index.html
            port: 80
          initialDelaySeconds: 15
          timeoutSeconds: 2
          periodSeconds: 5
          failureThreshold: 1
        ports:
        - containerPort: 9090
