apiVersion: v1
kind: Service
metadata:
  name: external-service  #other pods can use this FQDN to access the external service
spec:
  type: ExternalName  #set type to ExternalName
  externalName: docs.sectigo.com  #Service will proxy to FQDN
  ports:
  - port: 9000
    
