apiVersion: v1  # Kubernetes API version and resource type (Service)
kind: Service
metadata:
  name: nginx  # Name in the metadata is Name of Service(each Service gets a DNS entry)
  labels:
    app: nginx
spec:
  type: LoadBalancer  # Set Service type to Loadbalancer(normally used with cloud providers)
  selector:  # Service will apply to resources with a label of app: nginx
    app: nginx
  ports:
  - port: 80
    targetPort: 80
    