apiVersion: v1  # Kubernetes API version and resource type (Service)
kind: Service
metadata:
  name: nginx  # Name in the metadata is Name of Service(each Service gets a DNS entry)
  labels:
    app: nginx
spec:
  type: NodePort  # Set Service type to NodePort
  selector:  # Service will apply to resources with a label of app: nginx
    app: nginx
  ports:
  - port: 80
    name: http
    targetPort: 80
    nodePort: 31000  #Optionally set NodePort value(defaults between 30000-32767)
